env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "VpwgUIcPFOD2rX8KWaSGUPj1tdT/NV3/6MGzqrkJfgsoLUv+KnGlWsS0FkvSG9Gz4+TEwEPWeFR3z/SF1RnfcUUL4Mvf5P5Y5xU3JBkpNCZxpbJSwXmcLfRoB3sk4HM7awmJLOeAX0z9mKlOVFfR+gfC0k/JFUmU5hbAGaAC6Mhf3G6ls8MsnaTkHxit3EynIToaLJSvMd62fTZ6SgIs7sucpg4Jzs2CBiE5f1a/ozKcNeKy5IU0y8UAi9A0yFTQSXxaCZwMn8H6LPNq5yW4U+9HuZYalsxE0P9hZ65kz34grCGs0U9sygx7BlE+pkDlb/f0VS8QCT3n9yK0Vy/bg190vw82LffFHFylKj+yYxbNRSUtXCJQUI3gjLosbHAxti4KdPFutsq0U9B3j+iksVsqbYXCyLNF+yYrLXKx9MEf2FBtjHsvX9bet8edGlWAWL1DTlaGr4yX0tBlwHfvHSCPCnS+nrfh9mKMSz4ZCsgkB1cX8p6P3+bi4j9hraGt3cAG7cjAm/jn7fzB8VAES7sPokWThSG3qQTXIdFKnY2hBjlKtn9PyZY/adUWrtiimWC3wMKhnrXUhctXrFjwEu/zhKY4xQ5wcJ8HXQOb0qZpq25R6/ZIlN3Pa+Wfi1a317kL/YhITmxlMVQXI8lhX9y/IUmTZXeJYkzhL82y/As="

os:
  - linux
  - osx
dist: trusty
sudo: true
language:
  - c
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca- ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; brew install uriparser json-c ; fi

before_script:
  - echo "Installing gru"
  - wget https://github.com/orpiske/gru/tarball/master -O gru-head.tar.gz
  - mkdir gru && tar -xvf gru-head.tar.gz -C gru --strip-components=1
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then  pushd gru && mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=DEBUG -DCMAKE_VERBOSE_MAKEFILE=On -DCMAKE_INSTALL_PREFIX=/usr .. && make && sudo make install ; popd ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then  pushd gru && mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=DEBUG -DCMAKE_VERBOSE_MAKEFILE=On -DCMAKE_INSTALL_PREFIX=/usr/local .. && make && sudo make install ; popd ; fi
script:
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_VERBOSE_MAKEFILE=On -DBUILD_WITH_UNIT_TESTS=ON ..
  - make all
  - cd ..
addons:
  apt:
    packages:
      - liburiparser-dev
      - libjson0-dev
      - libcurl4-openssl-dev
  coverity_scan:
    project:
      name: "orpiske/bmic"
      description: "Broker Management Interface Client"
    notification_email: angusyoung@gmail.com
    build_command_prepend: "mkdir build && cd build && cmake -DBUILD_WITH_UNIT_TESTS=OFF -DCMAKE_BUILD_TYPE=RELEASE .."
    build_command: "make all"
    branch_pattern: coverity_scan
