env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
    - secure: "zZgLfFHU8OdmvpWCz5HfdGDDL/ry58xtttTtU3hfloRMOv2RT3cGN6W3HgF13mDZ13kS58gOkfEw5740s6/aZ6JvXHezGWy7A2Gjpshvw0cY3vmEvf68bFMhvJlw3XpXFXbTSsgl9h5NQvhFfmmzzkALxwBnWoUEpJrijyq20i/HD6+ayd6tUjHPg1PqD4Rz6FA9otu4f7y6lKIvtWRlKVeW7bV6EmdK09MumCM2tWiRe1cKBsyPKpLrf1XVON1IAQccOED49vgKK6KTHCYB+IsbA3qzkppMfl4XI3C1jFoZeLk60pAlMDsD2DUo6fRgtiBUkws0oKr8YZdeJxg3AsKAPfvEw2DwuOvgs12p3v6pwApRpy9iAyMQBiA9uG8PWtD6+O5xs9LMPrRRPTUWpU5A+cqIDZ/P1voFRjw5awZE4D8IWS5ZQ6L6G0ZVba/0JH4cOcSKjsX+j4RSSPZeVe/4DPlDEveKi5cenXM+hdFkIwXsMqUxVqYzcdlj0tcX3rJYpBNfevD2hQ2zws28GSX12NjI8ya3nzZRMD0opMEpZoKzhlnTYEstRwKki+Ieh4rPDx62BzkqIM3yw3gQfoBlZhNxRYcpFfpu296q1Fe+ny4LTWYuYPLFdY7f1xrCm0TbaThoBw1qtC7CzJfSDgXzYldd75u5dTLCkAQTGpM="
os:
- linux
sudo: true
language:
- c
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y cmake doxygen libjson-c-dev libcurl4-openssl-dev
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
before_script:
- wget https://github.com/orpiske/gru/tarball/master -O gru-head.tar.gz
- mkdir gru && tar -xvf gru-head.tar.gz -C gru --strip-components=1
- pushd gru && mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=/usr .. && make && sudo make install ; popd
- mkdir build
- cd build
- cmake -DCMAKE_BUILD_TYPE=RELEASE ..
script:
- make all
addons:
  coverity_scan:
    project:
      name: "orpiske/bmic"
      description: "Broker Management Interface Client"
    notification_email: angusyoung@gmail.com
    build_command_prepend: "mkdir build ; cd build && - cmake -DCMAKE_BUILD_TYPE=RELEASE .."
    build_command:   "make"
    branch_pattern: coverity_scan
